- name: Create new user
  ansible.builtin.user:
    name: "{{ new_username }}"
    shell: /bin/bash
    create_home: yes
    state: present
  when: new_username | length > 1

- name: Add new user to sudo group
  ansible.builtin.user:
    name: "{{ new_username }}"
    groups: sudo
    append: yes
  when: new_username | length > 1

- name: Set password for new user
  ansible.builtin.user:
    name: "{{ new_username }}"
    password: "{{ new_password | password_hash('sha512') }}"
  when: new_username | length > 1

- name: Create .ssh directory for new user
  ansible.builtin.file:
    path: "/home/{{ new_username }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ new_username }}"
  when: new_username | length > 1

- name: Generate new SSH key pair if needed
  delegate_to: localhost
  become: false
  community.crypto.openssh_keypair:
    path: "~/.ssh/id_ed25519"
    type: ed25519
    state: present
  when: new_username | length > 1

- name: Copy SSH public key
  ansible.builtin.authorized_key:
    user: "{{ new_username }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  when: new_username | length > 1
